apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Testing infrastructure
  - testing/validation-pods
  
  # Namespace-specific policies
  - policies/default
  - policies/infra
  - policies/observability
  - policies/security
  - policies/storage
  - policies/supabase

  # Monitoring and alerting
  - monitoring

# Enable to run tests but disable in production
# - testing/validation-jobs 