apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: production
    owner: platform-team
  name: infra
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: production
    owner: platform-team
  name: observability
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: production
    name: security
    owner: platform-team
  name: security
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: production
    owner: platform-team
  name: storage
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  dummy: value
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: observability
stringData:
  dummy: value
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: security
stringData:
  dummy: value
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: storage
stringData:
  dummy: value
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: boldorigins-io-tls
  namespace: infra
spec:
  dnsNames:
  - '*.boldorigins.io'
  - boldorigins.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: boldorigins-io-tls
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: rodrigo.mourey@boldorigins.io
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: infra
spec:
  chart:
    spec:
      chart: cert-manager
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.12.0
  install:
    remediation:
      retries: 3
    timeout: 10m
  interval: 30m
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
    timeout: 10m
  values:
    cainjector:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        runAsUser: 1001
      podSecurityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1001
    global:
      podSecurityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
    installCRDs: true
    podSecurityContext:
      fsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1001
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    startupapicheck:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        runAsUser: 1001
      podSecurityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi
    webhook:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        runAsUser: 1001
      podSecurityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: infra
spec:
  chart:
    spec:
      chart: ingress-nginx
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 4.12.0
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 30m
  timeout: 15m
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      config:
        enable-real-ip: "true"
        proxy-body-size: 100m
        use-forwarded-headers: "true"
      ingressClassResource:
        default: true
        enabled: true
        name: nginx
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
      service:
        externalTrafficPolicy: Local
        nodePorts:
          http: 30080
          https: 30443
        type: NodePort
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: infra
spec:
  chart:
    spec:
      chart: sealed-secrets
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      version: '>=2.9.0'
  interval: 30m
  values: null
