apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-kong-config
  namespace: supabase
data:
  kong.yml: |
    _format_version: "2.1"
    _transform: true

    services:
      - name: studio
        url: http://supabase-supabase-studio:3000
        routes:
          - name: studio-route
            paths:
              - /
            strip_path: false
        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - PATCH
                - DELETE
                - OPTIONS
                - HEAD
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - Authorization
              exposed_headers:
                - Content-Length
                - Content-Type
              credentials: true
              max_age: 3600
              preflight_continue: false

      - name: auth
        url: http://supabase-supabase-auth:9999
        routes:
          - name: auth-route
            paths:
              - /auth/v1/
            strip_path: true
        plugins:
          - name: cors

      - name: rest
        url: http://supabase-supabase-rest:3000
        routes:
          - name: rest-route
            paths:
              - /rest/v1/
            strip_path: true
        plugins:
          - name: cors

      - name: realtime
        url: http://supabase-supabase-realtime:4000
        routes:
          - name: realtime-route
            paths:
              - /realtime/v1/
            strip_path: true
        plugins:
          - name: cors

      - name: storage
        url: http://supabase-supabase-storage:5000
        routes:
          - name: storage-route
            paths:
              - /storage/v1/
            strip_path: true
        plugins:
          - name: cors 