---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 30m
  timeout: 15m
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    remediation:
      retries: 3
  chart:
    spec:
      chart: loki
      version: "6.27.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 30m
  values:
    loki:
      auth_enabled: false
      useTestSchema: true
      commonConfig:
        replication_factor: 1
        path_prefix: /var/loki

    singleBinary:
      enabled: true
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
        storageClass: local-path
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi
      extraEnvFrom:
        - secretRef:
            name: loki-minio-credentials
      serviceAccount: loki

    storage:
      type: s3
      s3:
        endpoint: minio.storage.svc.cluster.local:9000
        insecure: true
        bucketnames: loki-data
        chunks:
          bucket: loki-data
        ruler:
          bucket: loki-ruler
        admin:
          bucket: loki-admin

    monitoring:
      selfMonitoring:
        enabled: false
      lokiCanary:
        enabled: false

    test:
      enabled: false

    gateway:
      enabled: false
