---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: ">=5.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
        ring:
          kvstore:
            store: inmemory
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: 2020-05-15
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
    monitoring:
      selfMonitoring:
        enabled: false
      lokiCanary:
        enabled: false
    persistence:
      enabled: true
      size: 10Gi