---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: "6.27.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 30m
  values:
    loki:
      storage:
        type: s3
        s3:
          endpoint: minio.storage.svc.cluster.local:9000
          insecure: true
          bucketnames: loki-data
          access_key_id: ${MINIO_ACCESS_KEY}
          secret_access_key: ${MINIO_SECRET_KEY}
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      compactor:
        shared_store: s3
    deploymentMode: "simple"
    schemaConfig:
      configs:
        - from: "2023-01-01"
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            prefix: loki_index_
            period: 24h
    monitoring:
      selfMonitoring:
        enabled: false
      lokiCanary:
        enabled: false
    persistence:
      enabled: true
      size: 10Gi
    write:
      persistence:
        enabled: true
        size: 10Gi