---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 30m
  timeout: 15m
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    remediation:
      retries: 3
    cleanupOnFail: true
  chart:
    spec:
      chart: loki
      version: "6.15.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
        path_prefix: /var/loki
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2024-02-01"
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: loki_index_
              period: 24h
      structuredConfig:
        ruler:
          storage:
            type: local
            local:
              directory: /etc/loki/rules
          rule_path: /tmp/loki/rules
          ring:
            kvstore:
              store: inmemory
          enable_api: true

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
        storageClass: local-path
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi
      serviceAccount: loki

    monitoring:
      selfMonitoring:
        enabled: false
      lokiCanary:
        enabled: false
    test:
      enabled: false
    gateway:
      enabled: false

    # Use simple deployment mode
    backend:
      enabled: false
    read:
      enabled: false
    write:
      enabled: false

    # Set deploymentMode
    deploymentMode: SingleBinary
