---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: ">=5.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    singleBinary:
      replicas: 1
    monitoring:
      selfMonitoring:
        enabled: false
      lokiCanary:
        enabled: false
    storage:
      bucketNames:
        chunks: chunks
        ruler: ruler
        admin: admin
      type: s3
      s3:
        endpoint: minio.storage.svc.cluster.local:9000
        insecure: true
        bucketnames: loki-data
        access_key_id: minioadmin  # Default MinIO credentials
        secret_access_key: minioadmin  # Default MinIO credentials
    persistence:
      enabled: true
      size: 10Gi