---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: "6.27.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 30m
  values:
    loki:
      useTestSchema: true
      storage:
        type: s3
        bucketNames:
          chunks: loki-data
          ruler: loki-ruler
          admin: loki-admin
        s3:
          endpoint: minio.storage.svc.cluster.local:9000
          insecure: true
          bucketnames: loki-data
          access_key_id: ${ACCESS_KEY_ID}
          secret_access_key: ${SECRET_ACCESS_KEY}
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      compactor:
        shared_store: s3
    deploymentMode: "simple"
    monitoring:
      selfMonitoring:
        enabled: false
      lokiCanary:
        enabled: false
    persistence:
      enabled: true
      size: 10Gi
    gateway:
      affinity: {}
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      podAnnotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-minio: "kv/data/storage/minio"
        vault.hashicorp.com/role: "loki"
        vault.hashicorp.com/agent-inject-template-minio: |
          {{- with secret "kv/data/storage/minio" -}}
          export ACCESS_KEY_ID="{{ .Data.data.access_key_id }}"
          export SECRET_ACCESS_KEY="{{ .Data.data.secret_access_key }}"
          {{- end -}}
    read:
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi
      podAnnotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-minio: "kv/data/storage/minio"
        vault.hashicorp.com/role: "loki"
        vault.hashicorp.com/agent-inject-template-minio: |
          {{- with secret "kv/data/storage/minio" -}}
          export ACCESS_KEY_ID="{{ .Data.data.access_key_id }}"
          export SECRET_ACCESS_KEY="{{ .Data.data.secret_access_key }}"
          {{- end -}}
    write:
      persistence:
        enabled: true
        size: 10Gi
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi
      podAnnotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-minio: "kv/data/storage/minio"
        vault.hashicorp.com/role: "loki"
        vault.hashicorp.com/agent-inject-template-minio: |
          {{- with secret "kv/data/storage/minio" -}}
          export ACCESS_KEY_ID="{{ .Data.data.access_key_id }}"
          export SECRET_ACCESS_KEY="{{ .Data.data.secret_access_key }}"
          {{- end -}}
    backend:
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi