---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supabase
  namespace: supabase
spec:
  interval: 30m
  chart:
    spec:
      chart: ./charts/supabase
      sourceRef:
        kind: GitRepository
        name: supabase
        namespace: supabase
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  releaseName: supabase
  valuesFrom:
    - kind: ConfigMap
      name: supabase-values
      valuesKey: values.yaml
  values:
    image:
      tag: latest
    # Default values for Supabase
    # For more configuration options, refer to the Supabase Kubernetes documentation
    # https://github.com/supabase-community/supabase-kubernetes
    
    # PostgreSQL configuration
    postgres:
      enabled: true
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 250m
          memory: 1Gi
      persistence:
        enabled: true
        size: 20Gi
    
    # Storage configuration
    storage:
      enabled: true
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi
    
    # API configuration
    api:
      enabled: true
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi
    
    # Auth configuration
    auth:
      enabled: true
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi
    
    # Studio (Dashboard) configuration
    studio:
      enabled: true
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi
    
    # Ingress configuration
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: supabase.k3s.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: supabase-tls
          hosts:
            - supabase.example.com 