---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ui-grafana-creds
  namespace: observability
spec:
  encryptedData:
    grafana_password: AgCIDjeNKPODFwlpiV6xC1cw5yvPctEk4QHuHy6mnRMzkBLMuTBBRwdz6K809OB2fMLr36Q0H/jgKa4tVeichihIxc+7ttwiTF3nXqJy8OZbvgPBcuzLk9gLyoKAVNm57gmKGJ/Xe1ZYsHCSzQ84rYQyWYa36DrgyfboCLmaIiTdjSovNSlYtl/SlHNG7IdDFGxcZPZ1Iu4UbKdlKZ3eWpoj3iYD8vXi/OKB9KCX6ndkC9Mwz2/1gyE/u5ZQX67yZHToI2/N1+iX6tnlUIsvpA80QlsAzFPSVM68SQB5IkUEvnG1+iHWa8wn86GwnmDnBuYHTJ/L9isSnExsj/7mX9Ce7QuGR4ZywsMlgv0KJRRwDCDiuWxtYja3JRE29oWz0VYH9vG+qCpON5rJ/tMe5RqcbMPPNFZkxKzxSJSZWWvYR/w6GdPSWf1bN/ayiNX9uz2PMpOntl1yNLR+mgoZ/jNXfLC+5kbqr2RKCoGpyGEx4R3o+a/sn3G2WUyEZPZkw3r4edTQTQr1OqYxRh9GEdcmvDw0nBgQNbZeyjXLKFH4nMGD+OoX1VkSkkW/8wnocVMzLVaDZl8Pr6DpsM7Km2/VCCh9fOXhL9VUwjP2weQKh/O777i2SLUXFJv3t4tvHRGBj2UlIU8P7w0q6e26/hevhlKIFZ3kgL2bscGsMjUBhtlxl0GAm8DCpsKCMccvSXaogLBZJiZDkw8hwxVT
    grafana_username: AgBiATG4AcuPj5sL2jxFtNeJcJf7YgUkEQwPL0mRCUG24yfsCIss5pzzn4NiiKjVMcBil0+AZOXnM/nCECyzjuQEUxBg25HnQEfxS77w+Jrc/5IGqTOfbrQU7JYDHgmvpnvoSSdKo5oL4SxoVTAelBbJdWu/JnWVRGDiG5Gvz/iwE2aAwvSUN9sGMg3ZIm5YBTTbgp3QGqYgZ3IVf8jYgcjIw590UqwXgph5x75f92LRcLGkclX8DPcPYlTLY2k5gWbyEo6wkaNiPaCK1/FY1iXPTLB2sjaMDpmzFIkQnB+qAP8ifxHE5w6CqDLiZLtm9YpRLwpemAa1ya43F37jyukd3IqlAtiFTHADbE3bGo1Od//8RNqvFUnGVmsTStv4eGBSxryEThNBgULubpDydbCNIvSvOsY4g1IM0RHecp0YxdU7yfzWAG7IW8qMcekF/jCBlaUm3waj0ftDUz/VMvJUZ/PSCdV2Smx6PaOYk9T9G2yA8+baOLMR1QRPM9DQ8Fh0II50cu/nTtKdJX/nw1Z7myS/q40Tiizwhf8TkF+q2A9W52eJXOphtI2Fy/BBqA+W1VecY81wnJZZCvlOlnpGG1H+rK1krCNYMmW5PDzu6JHHh9EZXe92xgZNeFTADUXzWoJND5eUgW47BndomWdsne7KFrvytkGjdwElYJE4QYmDv4cTtlRdSNbM6n1oj0qKub/LmQ==
  template:
    metadata:
      creationTimestamp: null
      name: ui-grafana-creds
      namespace: observability
    type: Opaque
