---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ui-grafana-creds
  namespace: observability
spec:
  encryptedData:
    grafana_password: AgCzS1gG77sbiqXwfJ48XqmkBRWl7BJKleUXTtmg0ZuP22wVV02eA5ukUFy4pvvaIjDKpiOHZQilfPxhY8h5UWt3kBUNAE8Mydwa7EKkP66loj+z50Vvz/SpElmNAfqq0SuU14z/GStg+VWacBormikOZVo+HgOztoY1oPVtqdoZgW686p/1Y5HyPhKPvGowB1O/+q5qyk9tc/bkHhNdtHrzUM5AJMums6WN1E4QIfTGqZPJgSvaRWLlAZQBTo4ZffvX2HOzEoFenaDlO0cWpwlyi9yHVOZotmqZWNYJjCTAuwXPoFcnak3DdrGQp9QZQmokKs4cXmwmk4fRrUhnTe8Zw7YeZisuPTQzUVKhrTbmWgL54DJUpDddF5kg9gIP3Sy5GRRYUUTNdfwVKpbCc6fnsDQzGc4owzZVqo4TOCSECAuiQaHhwrAhYqL3sS/zYXwL/OqOHbSS001SJmMNEDGkTb2KGl/ONvDGLi/hnQmY2nqfiJRDG0DeBUlEvMGHAoSQbeS6Z8HDcqQmfvW+JEMh/1RtkVeRdTepHTYYrG7h++rN3hM+HzE7rfnx4U2dYiehUeOuP/Jlt+ZfDYDVGN7ex8N0bLG4bt8T5y272OiSBlKCXReobv4CtVQaCYLXJtZ3aXP29IZDy6K1jbyvygXkvYwfMdAYLs1ZpyDOzueLuUjrlWa7tuWaKn/EDFkqc//wxu7KPnLWYok27DQG
    grafana_username: AgB3AdLU8EGdw+PViZ+pMhof3xtMjc0hOx19ZlL6BHpLD66THiU5eqJsCBAcG7bmJe6XwmK3pqXxoKCExN4VwpJ2mLxgxeHYD3DWuC2yRaOlf3zg5X6YoQhwnDyurK6DW2XGXtirSzdZ9SEui+qAAQWZlkc2yGr+QZ4BDJ4bgYCLZJHnAZCezC7rDRDTPHmrBApyeZ0K8f23WvQqfoRX9j2ddzjOjq1sscIuz21CFPaYM2Ia20TXG89MYakWJcTvembXuzbQKWS8hNYb9iY/lhlrq6NlraiN2waGNL3WYAeAguZ70h/nfTITkylYsoQJwY+JMA3p8+gGbC/BTlR10IxRcT/q/2cHADtuLRNDsJE1hd2+IRuzO9u4/sXhhKFECN8nBYbf2nlIDBCFOpC2GbB3dh4leB6AD+qzD4NnOXr7yWl3oEj9+p5XwGAx4BbCndUruDUVxPT/uBE8Luqm6Pp9gPa33LtbZ4KkOoci/ECZsiDME46CCvd4sFJDS2uSkOsmuaicyyPH8vqmgvxLAZe48RxRUAnX6g0FWW5oODdyVe1jrsJAybF5FKyJHzTEiJ4i9NAsTTcWxWNWuLt/ChNfeLzwLO2lbZSP2SVAc9BxBBjOO5OJ3w4rQAIvyTZEwdoh2lCRKmSBArOC3Y/tz2GuXEjZj4VuBbFHM17f6xeNtjjJ9enepklSAsyJaPpWlN00e+rtaw==
  template:
    metadata:
      creationTimestamp: null
      name: ui-grafana-creds
      namespace: observability
    type: Opaque
