---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tempo
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo
      version: "1.18.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    tempo:
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 250m
          memory: 1Gi
      persistence:
        enabled: true
        size: 10Gi
        storageClassName: local-path
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
      server:
        http_listen_port: 3100
      distributor:
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: "0.0.0.0:4317"
              http:
                endpoint: "0.0.0.0:4318"
      ingester:
        trace_idle_period: "30s"
        max_block_bytes: 1_000_000
        max_block_duration: "5m"
      query_frontend:
        query:
          backend: local
    containerSecurityContext:
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
    startupProbe:
      httpGet:
        path: /ready
        port: 3100
      failureThreshold: 30
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /ready
        port: 3100
      initialDelaySeconds: 180
      periodSeconds: 30
      timeoutSeconds: 1
    readinessProbe:
      httpGet:
        path: /ready
        port: 3100
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 1