---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tempo
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    tempo:
      persistence:
        enabled: true
        size: 10Gi
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"
      server:
        http_listen_port: 3200
      frontend:
        enabled: true
      ingester:
        trace_idle_period: "30s"
        max_block_bytes: 1_000_000
        max_block_duration: "5m"