---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: infra
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: ">=4.7.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      config:
        enable-real-ip: 'true'
        proxy-body-size: 100m
        use-forwarded-headers: 'true'
      ingressClassResource:
        default: true
        enabled: true
        name: nginx
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
      service:
        externalTrafficPolicy: Local
        type: LoadBalancer