---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: infra
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      config:
        enable-real-ip: 'true'
        proxy-body-size: 100m
        use-forwarded-headers: 'true'
        proxy-connect-timeout: '180'
        proxy-read-timeout: '180'
        proxy-send-timeout: '180'
      ingressClassResource:
        default: true
        enabled: true
        name: nginx
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
      service:
        enabled: true
        externalTrafficPolicy: Local
        ports:
          http: 80
          https: 443
        targetPorts:
          http: http
          https: https
        type: LoadBalancer
      hostPort:
        enabled: true
        ports:
          http: 80
          https: 443
      publishService:
        enabled: true