---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: infra
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      hostNetwork: false
      dnsPolicy: ClusterFirst
      replicaCount: 2
      config:
        enable-real-ip: 'true'
        proxy-body-size: 100m
        use-forwarded-headers: 'true'
        proxy-connect-timeout: '60'
        proxy-read-timeout: '60'
        proxy-send-timeout: '60'
      ingressClassResource:
        default: true
        enabled: true
        name: nginx
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
      service:
        enabled: true
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: "true"
        ports:
          http: 80
          https: 443
        targetPorts:
          http: http
          https: https
        type: LoadBalancer
      publishService:
        enabled: true
      extraArgs:
        enable-ssl-passthrough: true
      containerPort:
        http: 80
        https: 443
        healthz: 10254
      podSecurityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsNonRoot: true
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      readinessProbe:
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      podDisruptionBudget:
        enabled: true
        minAvailable: 1