---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: vault-secrets-operator
      version: ">=0.3.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 12h
  values:
    controller:
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
    defaultVaultConnection:
      enabled: true
      address: http://vault.security.svc.cluster.local:8200
    defaultAuthMethod:
      enabled: true
      method: kubernetes
      mount: kubernetes 