apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
type: Opaque
stringData:
  dummy: value
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: security
type: Opaque
stringData:
  dummy: value
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: observability
type: Opaque
stringData:
  dummy: value
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: storage
type: Opaque
stringData:
  dummy: value 