---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: infra
spec:
  interval: 30m
  chart:
    spec:
      chart: sealed-secrets
      version: ">=2.9.0"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      interval: 12h
  values:
    # Your values here if needed