---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: infra
spec:
  chart:
    name: sealed-secrets
    repository: https://charts.bitnami.com/bitnami
  releaseName: sealed-secrets