---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vault
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: ">=0.24.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 12h
  values:
    server:
      dataStorage:
        enabled: true
        size: 10Gi
      standalone:
        enabled: true
      ha:
        enabled: false
      injectors:
        enabled: true
        sidecar:
          enabled: true