---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: security
spec:
  chart:
    name: vault
    repository: https://helm.releases.hashicorp.com
  releaseName: vault
  values:
    server:
      ha:
        enabled: true
        raft:
          enabled: true
      injectors:
        enabled: true
        sidecar:
          enabled: true