---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vault
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: ">=0.24.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 12h
  values:
    server:
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi
      dataStorage:
        enabled: true
        size: 10Gi
      standalone:
        enabled: true
        config: |
          ui = true
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_cert_file = "/vault/tls/tls.crt"
            tls_key_file = "/vault/tls/tls.key"
            tls_disable = false
          }
          storage "file" {
            path = "/vault/data"
          }
      volumes:
        - name: vault-tls
          secret:
            secretName: vault-tls
      volumeMounts:
        - name: vault-tls
          mountPath: /vault/tls
          readOnly: true
      ha:
        enabled: false
      # Disable the default ingress as we're using our own
      ingress:
        enabled: false
      injectors:
        enabled: true
        sidecar:
          enabled: true
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi