---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vault
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: ">=0.24.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 12h
  values:
    server:
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi
      dataStorage:
        enabled: true
        size: 10Gi
        storageClass: local-path
      auditStorage:
        enabled: false
      standalone:
        enabled: true
        config: |
          ui = true
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_disable = false
            tls_cert_file = "/vault/tls/tls.crt"
            tls_key_file = "/vault/tls/tls.key"
          }
          storage "file" {
            path = "/vault/data"
          }
      ha:
        enabled: false
        replicas: 1
      # Disable the default ingress as we're using our own
      ingress:
        enabled: false
      extraEnvironmentVars:
        VAULT_SKIP_VERIFY: "false"
      # Add volume mounts for TLS certificates
      extraVolumes:
        - type: secret
          name: vault-tls
          path: "/vault/tls"
      # Remove tls-skip-verify from readiness probe
      readinessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true&sealedok=true&uninitok=true"
      injector:
        enabled: true
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
    defaultVaultConnection:
      enabled: true
      address: "https://vault.boldorigins.io"
      skipTLSVerify: false