---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: minio
      version: "15.0.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
  values:
    mode: standalone
    auth:
      existingSecret: minio-credentials
    persistence:
      enabled: true
      size: 10Gi
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    service:
      type: ClusterIP