---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: minio
      version: "5.4.0"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
  values:
    mode: standalone
    auth:
      existingSecret: minio-credentials
    persistence:
      enabled: true
      size: 10Gi
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    service:
      type: ClusterIP
      ports:
        - name: http
          port: 9000
          targetPort: 9000
          protocol: TCP
        - name: http-console
          port: 9001
          targetPort: 9001
          protocol: TCP
    environment:
      MINIO_SERVER_URL: "https://minio.boldorigins.io/api"
      MINIO_BROWSER: "on"
      MINIO_DOMAIN: "minio.boldorigins.io"
    livenessProbe:
      httpGet:
        path: /minio/health/live
        port: http
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /minio/health/ready
        port: http
      initialDelaySeconds: 5
      periodSeconds: 10
    startupProbe:
      httpGet:
        path: /minio/health/live
        port: http
      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 60
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      fsGroup: 2000
    containerSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL