---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: minio
      version: "12.0.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
  values:
    mode: standalone
    auth:
      rootUser: minioadmin
      rootPassword: minioadmin
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        memory: 1Gi
    service:
      type: ClusterIP