---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: storage
spec:
  encryptedData:
    root-password: AgA/q6iMjLXcWQOifUk7cJR6mh5L3F0nFAeWtizyhnD9EsNSSNJMDPas8YTwqdH0mpjW4bBvqtmCp6niAaR+AKTRskCC6ILomgwMYIobJD6Mmq4scpXBHpsGPRXSyBPBlEjQd1vs/nF0oXtEKmiQQrNaPZjmX9XBKWlTzM8NkUV5vY15Jzjt9NLUss97WyPERsCzWdDjJj/6BwT0CpnuEbKmqpFhHQ6PdMKXaNX/hCGdyydwyIf4SVTS9cpe6RECNYZ5KzvqzphJ52/thIFucF9aoVHMD2Ny796EoChab7aREChEib/PHEXmzENPgG7rXBI35XBxGmLuCyzc+yOJBAxOpJiiaEDUDCKbdcXuLPMGRXocaex1+kJ9xUHLq/+BAagbtDUw+d5JKBVsZCp9rbDBvdvYe80idvvHEyoS1lZ7lqkpuyuU7Zpo8x9xLcRJ6tw3MdnwrbY11PdurmikZMe12zZuLAijGGczYXv1jij62DPCHBsztGZNUaUAHXCSPHBS98A79tZTOs5MJHpeyDil1TFRLDvhI8h97QXAbVKeqwuHzW6U6bDP93r3GrbzwJGuS05okLx32JaD1awrMbHdsb7crivervLDdYsHlMOpOB+0ioNpBbdXivA0e5GL1gi94oXPDoENRvoAYpHNTFg5W/l83c2H0nJEohNPjrJpb7nzlFo0IQV1CzQSbUp5bIciMF1Gh83aljspiH76ireYwWBx/SMxy34LKOucrJ9VTOcQNLoocBgP
    root-user: AgBXXhUQce/RWXzAMPigY9ZhKzcDkqMkWOf5fE4l0tos0TsOeAefyExgcDjWD7m26D9tXSXPDsRls8vdRDXY/lq6fFBG3FLgmD83Dm+cCAc5P3+rhhm1+Ho5M7e6SyO7FdrvU0OcXAQNK/Rmv99ErOwOM6TV7Re9IU2Ne43EYeYeVzjX/tIuT0zrciEfJEIRW2ERUBhKdxTVRbFqsCOi0zY+z9WRIFzNJxijq0cOlV5lj6P3lOtUygyfMIqf0VlhbpJEyghjsusXr3dxTZm4rDG8WH0uVxNSAhV5JGZ8cozXORqGm/RRVCr2xdHlubLey2UH8BFrbxvDwgAAtaCHwrPpU54GE1KXMY8YvR0U4TTHtQGV+jKMgxmUy843BA3TsYiUvCM1wd1vDGFWTeAGOEdP15p+Kh5PA0RIozFf/wUj/szLmXa8vA1OKL7SW0f0bFZU1GinJGng5hToXeIGj0Se0K/h/PzmqDgjYoqIAa0Xvd98RLl/pNE1DRKYrFFH3wN8e3CvzOC8pBWMGXhc1PaZQ+4rkKQHNYv0K02OMu/62pEL3G+iCmlJjCLPlUs8gZUSiPjaWZqTRxM5hkCF50dEI3H1Pd3I0Xcf7IIZ2Jz6ZHcyw2wMsS0tOs/uJjLIUMM2fT+88cogRD6zRBuIzKgTdXzweYlMPFhHzMSlVD+MFJ60ZQKDhQRELU4CkPD57kN45Jz6enVEcVjK4uhcZyq4fiZIiA==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: storage
