---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: storage
spec:
  encryptedData:
    root-password: AgBCULN4NADEYWa/x+9NH5DcxrwTx/v+ZO/sV7QSjRiveMLQ9aNGswTYE3L4wqj5Y9/LB8wdmJYGonKFo3gveqR1kXjmbB1G1WBlFlS9kW5n3g7CN8KdyOvCkHc1IVaAzecdKHzqv11qxn7rwz1WWgHKnFvNmwGXwHKXsgVlzMdCGUymiX0jKhrw4AR7SuvRtgzDd/b0jFedf+TpFYJ8yHh6ZAm11uWCpbBgfr0FPjGEZqPbng9ZeVzLzvJ0zUNPuMXPO4X/uCu3C7AOz+pOPwRkifC/rFhQtSTkc3236lPjkozoTf+KaMjntVOgJo17Wlw9GCkIt+rn4/dbKJ1fcgkO7D3j/KK0HkyxGJLzxxdpWhjwTU6LeQP0Sx6YCARwS+SerOEDaFzcPazc8hlNMRrS6gehAWwfY21rouCk1PZ8mUOOf51Rvd4veWfeGXhNPiXwIDjTfZbY3LAGi8+Ac/PIc5l1nPrvPI4JwewzmvX5BbeUeUzrcPHHsSYT9qGLnd8qknsrs840dvsbLUd+YS//Hago96Kp8Ck1oVXoQspZ1SFBmgQ5DEQ2PDWbB7/ge7xQybByDh2GVVKN8gS6KK6oC04Gaj6jXxmXRFwvr2qW+xFWWNJWbkRyOUutrkY9EUWKy6YSCWUOoFEQc4q8fdVrKBPXS6kJrgserPHmXWL2UDPpLbUeU9mnf/UlfwebJWiZLYJhDX/yMM51dagtVA==
    root-user: AgC9v/5arDRvP0x3uXZwCad2DM/x5Yfk5KrINaRdikdgv/FlpcxntD6YEsUhchffDBwmglidZx0Z54f4kqhv0FtMgIgrG/IM6Vxyi0pk4T6JwBjB98SlWU9QSxxJiFxr7aGILdxZLWJzzydpHksFD0c0Bj7fsFCndUfeX3hedotgaFaZUNxsaJmtTWaIFATzp5JlvpNRuvXqkHALZcR7HObw3HQrymMgMeyiXCPIk3Z5zLe2BKdpQxSNVWArGbQoeySr3KfszwrDansNmN2hqyFMWoa0Qg3VxEMl92yvHzSGN5rh3VShLxvcu6kngsg9lZrJ9R5JwAJXPMq7MSFn9bNzn99sz23pI82KlrnfDl1ig1ikg3tPdeszRjzP6Uzqv7qoa5cQEPi5s4z0UKlj2CYC1M+N2f4DCbNChJydCHdI6x7Ok+E9vQC3r7/hdIF0yQkIrq4iotjcvvFzKUKvgQfa1oO0xiKJpeFr0jFul4DHS96vxtP6RdVfHHWirNx5G17wnxoH8WmiDnKLprRy5D7fg2qhWOFufVwknfANDJ9zlZWmRD4TFYVpZ9Cw+ESYALS5nyEvUleYb4Y6I2ibDzD16ifkwkhARrF06aC8F733BVYndlYNIA7o9cvrD1/wYsKOTsIvPgvcUvtpSnHCDMhH2RM3wU7bttAUlZD96EYHAHzsnSb7ylofPhq3uFz3oOO+bSfTBA==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: storage
    type: Opaque
