---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metallb
  namespace: infra
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.14.3"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    prometheus:
      serviceMonitor:
        enabled: false  # Disable service monitor for now until we have proper Prometheus setup
    speaker:
      frr:
        enabled: false 