apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-hetzner
  namespace: infra
spec:
  template:
    spec:
      containers:
      - name: cert-manager-webhook-hetzner
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi 