---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - kustomization-infrastructure-core.yaml
  - kustomization-infrastructure-cert-manager-config.yaml
  - kustomization-infrastructure-security.yaml
  - kustomization-infrastructure-observability.yaml
  - kustomization-infrastructure-storage.yaml
  - kustomization-infrastructure-supabase.yaml