---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../repositories
  - gitrepository.yaml
  - kustomization-infrastructure-core.yaml
  - kustomization-infrastructure-observability.yaml
  - kustomization-infrastructure-security.yaml
  - kustomization-infrastructure-storage.yaml