---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-core
  namespace: flux-system
spec:
  interval: 30m
  path: "cluster/core"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure-repo
  dependsOn: []  # This is the first to be applied
  wait: true
  timeout: 5m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: cert-manager
      namespace: infra
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: ingress-nginx
      namespace: infra
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: sealed-secrets
      namespace: infra 