---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-security-policies
  namespace: flux-system
spec:
  interval: 30m
  path: "cluster/security/gatekeeper/policies"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-security
  wait: true
  timeout: 5m 