---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
resources:
  - kustomization-infrastructure-core.yaml
  - kustomization-infrastructure-observability.yaml
  - kustomization-infrastructure-security.yaml
  - kustomization-infrastructure-storage.yaml