---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure-security
  namespace: flux-system
spec:
  interval: 10m
  path: cluster/security
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure-repo
  validation: client