---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-storage
  namespace: flux-system
spec:
  interval: 30m
  path: "cluster/storage"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure-repo
  dependsOn:
    - name: infrastructure-core