---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: "cluster/core, cluster/observability"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure-repo
  validation: client