---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure-storage
  namespace: flux-system
spec:
  interval: 10m
  path: cluster/storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure-repo
  validation: client