---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kustomization-infrastructure-core.yaml
  - kustomization-infrastructure-observability.yaml
  - kustomization-infrastructure-security.yaml
  - kustomization-infrastructure-storage.yaml
  - gotk-components.yaml
  - gotk-sync.yaml
  - ../repositories