---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-core
  namespace: flux-system
spec:
  interval: 30m
  path: "cluster/core"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure-repo
  dependsOn: []  # This is the first to be applied 