---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cert-manager-config
  namespace: flux-system
spec:
  interval: 30m
  path: "cluster/core/cert-manager/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
  dependsOn:
    - name: infrastructure-core
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
        optional: true 