---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  chart:
    name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
  releaseName: kube-prometheus-stack
  values:
    grafana:
      dashboardProviders:
        dashboards:
          default:
            enabled: true
    prometheus:
      prometheusSpec:
        retention: 7d