---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: core
resources:
  # Namespaces first
  - namespaces/namespace-infra.yaml
  - namespaces/namespace-observability.yaml
  - namespaces/namespace-security.yaml
  - namespaces/namespace-storage.yaml
  # Then other resources
  - cert-manager
  - ingress
  - secrets
  - secrets/cluster-secrets.yaml
  # TLS resources last (after cert-manager is ready)
  - tls