---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/helmrelease.yaml
  - ingress/helmrelease.yaml
  - namespaces/namespace-infra.yaml
  - namespaces/namespace-observability.yaml
  - namespaces/namespace-security.yaml
  - secrets/helmrelease.yaml