---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: core
resources:
  # First namespaces
  - namespaces/namespace-infra.yaml
  - namespaces/namespace-observability.yaml
  - namespaces/namespace-security.yaml
  - namespaces/namespace-storage.yaml
  # Then repositories
  - repositories
  # Then other resources
  - cert-manager/base
  - cert-manager/config
  - ingress
  - secrets
  - secrets/cluster-secrets.yaml