---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: core
resources:
  # First namespaces
  - namespaces/namespace-infra.yaml
  - namespaces/namespace-observability.yaml
  - namespaces/namespace-security.yaml
  - namespaces/namespace-storage.yaml
  # Then repositories
  - repositories
  # Then MetalLB base (HelmRelease) first
  - metallb/base
  # Other resources
  - cert-manager/base
  - ingress
  - secrets
  - secrets/cluster-secrets.yaml
  # MetalLB config last (after CRDs are installed)
  - metallb/config