---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: core
resources:
  # Namespaces first
  - namespaces/namespace-infra.yaml
  - namespaces/namespace-observability.yaml
  - namespaces/namespace-security.yaml
  - namespaces/namespace-storage.yaml
  # Then other resources
  - cert-manager
  - ingress
  - secrets
  - secrets/cluster-secrets.yaml
healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta2
    kind: HelmRelease
    name: cert-manager
    namespace: infra
  - apiVersion: helm.toolkit.fluxcd.io/v2beta2
    kind: HelmRelease
    name: ingress-nginx
    namespace: infra
  - apiVersion: helm.toolkit.fluxcd.io/v2beta2
    kind: HelmRelease
    name: sealed-secrets
    namespace: infra