---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: gatekeeper
      version: ">=3.12.0"
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
      interval: 12h