---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: gatekeeper
      version: ">=3.12.0"
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
      interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    postInstall:
      labelNamespace:
        enabled: false
    postUpgrade:
      labelNamespace:
        enabled: false
    auditInterval: 300
    constraintViolationsLimit: 100
    audit:
      enabled: true
    validatingWebhookTimeoutSeconds: 3
    mutatingWebhookTimeoutSeconds: 3