apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # First install Gatekeeper
  - base/helmrelease.yaml
  # Wait for CRDs and deployment
  - wait.yaml
  # Apply templates and constraints
  - policies/templates/
  - policies/constraints/ 