apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # First install Gatekeeper
  - base/
  # Wait for CRDs and deployment
  - wait.yaml
  # Then apply templates and constraints
  - policies/ 