apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # First install Gatekeeper
  - base/helmrelease.yaml
  # Wait for CRDs
  - wait.yaml
  # Create a separate directory for templates and constraints
  - policies/templates/
  - policies/constraints/
  # Templates first
  - policies/templates/container-limits-template.yaml
  - policies/templates/nonroot-template.yaml
  - policies/templates/required-labels-template.yaml
  # Then constraints
  - policies/constraints/container-limits.yaml
  - policies/constraints/nonroot.yaml
  - policies/constraints/required-labels.yaml 