apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-gatekeeper-templates
  namespace: security
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "false"
spec:
  template:
    spec:
      serviceAccountName: gatekeeper-admin
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Wait for each template to be established
          kubectl wait --for=condition=established --timeout=60s crd/k8scontainerlimits.constraints.gatekeeper.sh &&
          kubectl wait --for=condition=established --timeout=60s crd/k8snonroot.constraints.gatekeeper.sh &&
          kubectl wait --for=condition=established --timeout=60s crd/k8srequiredlabels.constraints.gatekeeper.sh
      restartPolicy: OnFailure
  backoffLimit: 3 