apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-gatekeeper-crds
  namespace: security
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "false"
spec:
  template:
    spec:
      serviceAccountName: gatekeeper-admin
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - kubectl
        - wait
        - --for=condition=established
        - --timeout=60s
        - crd/constrainttemplates.templates.gatekeeper.sh
      restartPolicy: OnFailure
  backoffLimit: 3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gatekeeper-admin
  namespace: security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatekeeper-crd-waiter
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gatekeeper-crd-waiter
subjects:
- kind: ServiceAccount
  name: gatekeeper-admin
  namespace: security
roleRef:
  kind: ClusterRole
  name: gatekeeper-crd-waiter
  apiGroup: rbac.authorization.k8s.io 