apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-gatekeeper-crds
  namespace: security
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "false"
spec:
  template:
    spec:
      serviceAccountName: gatekeeper-admin
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Wait for Gatekeeper CRDs
          echo "Waiting for Gatekeeper CRDs..."
          kubectl wait --for=condition=established --timeout=120s crd/constrainttemplates.templates.gatekeeper.sh &&
          kubectl wait --for=condition=established --timeout=120s crd/configs.config.gatekeeper.sh || exit 1

          # Wait for Gatekeeper deployment
          echo "Waiting for Gatekeeper deployment..."
          kubectl wait --for=condition=available --timeout=120s -n security deployment/gatekeeper-controller-manager || exit 1

          # Wait for webhook to be ready
          echo "Waiting for webhook to be ready..."
          until kubectl get validatingwebhookconfigurations gatekeeper-validating-webhook-configuration; do
            echo "Waiting for webhook configuration..."
            sleep 2
          done

          echo "All components are ready!"
      restartPolicy: OnFailure
  backoffLimit: 5
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gatekeeper-admin
  namespace: security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatekeeper-crd-waiter
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gatekeeper-crd-waiter
subjects:
- kind: ServiceAccount
  name: gatekeeper-admin
  namespace: security
roleRef:
  kind: ClusterRole
  name: gatekeeper-crd-waiter
  apiGroup: rbac.authorization.k8s.io 