apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: boldorigins-io-tls
  namespace: infra
spec:
  dnsNames:
  - boldorigins.io
  - grafana.boldorigins.io
  - vault.boldorigins.io
  - minio.boldorigins.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: boldorigins-io-tls
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: rodrigo.mourey@boldorigins.io
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx 