apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: supabase-smtp
  namespace: supabase
spec:
  type: kv-v2
  mount: secret
  path: supabase/smtp
  destination:
    create: true
    name: supabase-smtp
  vaultAuthRef: default 