apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: cert-manager-webhook-hetzner
    meta.helm.sh/release-namespace: infra
  creationTimestamp: "2025-02-21T15:26:58Z"
  generation: 1
  labels:
    app: cert-manager-webhook-hetzner
    app.kubernetes.io/managed-by: Helm
    chart: cert-manager-webhook-hetzner-1.3.1
    heritage: Helm
    release: cert-manager-webhook-hetzner
  name: cert-manager-webhook-hetzner
  namespace: infra
  resourceVersion: "159951"
  uid: cfff071b-47a6-4bb4-aa71-390bd06d6d8e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cert-manager-webhook-hetzner
      release: cert-manager-webhook-hetzner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cert-manager-webhook-hetzner
        release: cert-manager-webhook-hetzner
    spec:
      containers:
      - args:
        - --tls-cert-file=/tls/tls.crt
        - --tls-private-key-file=/tls/tls.key
        - --secure-port=8443
        env:
        - name: GROUP_NAME
          value: acme.yourdomain.tld
        image: ghcr.io/vadimkim/cert-manager-webhook-hetzner:1.3.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cert-manager-webhook-hetzner
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tls
          name: certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: cert-manager-webhook-hetzner
      serviceAccountName: cert-manager-webhook-hetzner
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: cert-manager-webhook-hetzner-webhook-tls
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-02-21T15:27:11Z"
    lastUpdateTime: "2025-02-21T15:27:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-02-21T15:26:58Z"
    lastUpdateTime: "2025-02-21T15:27:11Z"
    message: ReplicaSet "cert-manager-webhook-hetzner-586ccbbf65" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
