---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: falco
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: falco
      version: ">=3.0.0"
      sourceRef:
        kind: HelmRepository
        name: falco-security
        namespace: flux-system
      interval: 12h
  values:
    # Enable Prometheus metrics
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    
    # Configure logging to work with Loki
    json_output: true
    json_include_output_property: true
    
    # Configure Falco exporter for better Prometheus metrics
    falco-exporter:
      enabled: true
      serviceMonitor:
        enabled: true
    
    # Enable audit logs
    auditLog:
      enabled: true
    
    # Configure rules output format
    rules:
      # Send output in JSON format for better integration
      outputFormat: json