---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: falco
  namespace: security
spec:
  chart:
    spec:
      chart: falco
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: falco-security
        namespace: flux-system
      version: '>=3.0.0'
  interval: 30m
  values:
    # Enable audit logs
    auditLog:
      enabled: true
    # Configure Falco exporter for better Prometheus metrics
    falco-exporter:
      enabled: true
      serviceMonitor:
        enabled: true
    json_include_output_property: true
    # Configure logging to work with Loki
    json_output: true
    # Enable Prometheus metrics
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    # Configure rules output format
    rules:
      # Send output in JSON format for better integration
      outputFormat: json