---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: falco
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: falco
      version: ">=3.0.0"
      sourceRef:
        kind: HelmRepository
        name: falco-security
        namespace: flux-system
      interval: 12h