apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNonRoot
metadata:
  name: pods-must-run-as-nonroot
spec:
  match:
    excludedNamespaces:
      - kube-system
      - flux-system
      - cert-manager
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaceSelectors:
      - matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: In
            values: ["cert-manager"]
    excludedResources:
      - name: "*-acmesolver-*"
        kinds: ["Pod"] 