apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: require-environment-label
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
    labelSelector:
      matchExpressions:
        - key: kustomize.toolkit.fluxcd.io/name
          operator: In
          values: ["infrastructure-core", "infrastructure-security", "infrastructure-observability", "infrastructure-storage"]
  parameters:
    labels: ["environment", "owner"] 