apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: require-environment-label
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
    excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "default", "flux-system", "gatekeeper-system"]
  parameters:
    labels: ["environment", "owner"] 