grafana:
  persistence:
    enabled: true
    storageClassName: local-path
    size: 5Gi
  adminPassword: admin
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      kubernetes:
        gnetId: 15757
        revision: 1
        datasource: Prometheus
      security-falco:
        gnetId: 11915
        revision: 1
        datasource: Prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
  podSecurityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472 