---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: infra
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "v1.12.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 12h
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    installCRDs: true
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
      fsGroup: 1001
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    webhook:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
    cainjector:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
    startupapicheck:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi