---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: infra
spec:
  addresses:
    - 147.93.89.31/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: infra
spec:
  ipAddressPools:
    - default 