---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: infra
spec:
  addresses:
    - 147.93.89.31-147.93.89.31  # Node IP
    - 147.93.89.100-147.93.89.120  # Additional IPs
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: infra
spec:
  ipAddressPools:
    - default 