---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: infra
spec:
  addresses:
    - 147.93.89.100-147.93.89.120  # Allocating a range of 21 IPs for load balancers
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: infra
spec:
  ipAddressPools:
    - default 